version: '2'
services:
  web:
    image: $$REGISTRY$$/$$PROJECT$$/$$JOB_NAME$$:$$BUILD_TAG$$
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  lb:
    image: rancher/lb-service-haproxy:${LB_TAG}
    ports:
    - 8989:8989/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'